### ISSUE TITLE
关于侧边栏导航的问题

### ISSUE THREAD

**Issue by Hongwei-Qiu** [mengdu/vue-element-admin-tpl#10]
我想把接口的数据放到左边的导航栏,通过改接口字段属性实现了,但有些问题,所以我改了vmenu文件夹里的menus-list.vue文件,什么作用都没变化

**Comment by mengdu** [comment]
配置目录在components/menus.js里配置就行


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Hongwei-Qiu** [comment]
我是想调接口里的数据




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蓝月萧枫"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 上午10:15
收件人:&nbsp;"mengdu/vue-element-admin-tpl"<vue-element-admin-tpl@noreply.github.com&gt;;
抄送:&nbsp;"等梦归"<1614837845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengdu/vue-element-admin-tpl] 关于侧边栏导航的问题 (#10)




配置目录在components/menus.js里配置就行
 
 From gitme Android

**Comment by Hongwei-Qiu** [comment]
我改了这里的没作用




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蓝月萧枫"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 上午10:15
收件人:&nbsp;"mengdu/vue-element-admin-tpl"<vue-element-admin-tpl@noreply.github.com&gt;;
抄送:&nbsp;"等梦归"<1614837845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengdu/vue-element-admin-tpl] 关于侧边栏导航的问题 (#10)




配置目录在components/menus.js里配置就行
 
 From gitme Android

**Comment by Hongwei-Qiu** [comment]
&nbsp;想通了,谢谢你的回复,用错组件呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蓝月萧枫"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 上午10:15
收件人:&nbsp;"mengdu/vue-element-admin-tpl"<vue-element-admin-tpl@noreply.github.com&gt;;
抄送:&nbsp;"等梦归"<1614837845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengdu/vue-element-admin-tpl] 关于侧边栏导航的问题 (#10)




配置目录在components/menus.js里配置就行
 
 From gitme Android

**Comment by mengdu** [comment]
dev分支代码比较新，和在线例子一样，当然还没有时间写完善，可以关注下


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Hongwei-Qiu** [comment]
你好，又打扰了，就是我设置代理后，控制台报403，但是我vu脚手架新建一个项目没问题



&nbsp;想通了,谢谢你的回复,用错组件呢




------------------ 原始邮件 ------------------
发件人:&nbsp;"蓝月萧枫"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 上午10:15
收件人:&nbsp;"mengdu/vue-element-admin-tpl"<vue-element-admin-tpl@noreply.github.com&gt;;
抄送:&nbsp;"等梦归"<1614837845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengdu/vue-element-admin-tpl] 关于侧边栏导航的问题 (#10)




配置目录在components/menus.js里配置就行
 
 From gitme Android
