### ISSUE TITLE
app-footer布局问题

### ISSUE THREAD

**Issue by MonsterQueLLa** [mengdu/vue-element-admin-tpl#2]
项目可能到本地 运行发现app-footer组件无法位于地步 认真研究了下 elementUI的布局容器还是无法解决，我浏览了你发布的预览项目没有该问题，希望给个解决方案 ，谢谢

**Comment by mengdu** [comment]
`·app-footer` 组件并没有黏贴底部的功能，我实现是main主体的盒子 `min-height:100%` 达到的，当然整体布局还是基于饿了么的布局组件 `el-container`、`el-main`、`el-footr`等组件结合实现的。

请看 `app-view` 组件里的代码，
![image](https://user-images.githubusercontent.com/11366654/36630274-afc34578-199e-11e8-8c9d-c7199e5015c0.png)
