### ISSUE TITLE
local 环境为什么打开画面比例不对

### ISSUE THREAD

**Issue by boysfantasy** [mengdu/vue-element-admin-tpl#3]
我电脑1920像素，页面body却只有1097.14像素，画面缩放比例出现问题。图标 文字整体变大。请问下为什么，谢谢

**Comment by mengdu** [comment]
@boysfantasy 请提供截图。
检查你浏览器是不是缩放了。

**Comment by boysfantasy** [comment]
@mengdu 我页面没有放大，但是好像打开项目就会自动放大 ，之后crtl+0回复原样后，就可以了。公司的电脑是这样 家里的电脑是正常的，不懂是啥原因。可能游览器会保存页面地址缩放的问题吧
